name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        IMAGE_TAG="jobseeker-ui:latest"
        docker build -t $IMAGE_TAG .
  
        
    - name: Run Docker container
      run: |
        docker run --name jobseeker-ui_container -d -p 3100:6000 jobseeker-ui:latest
